const keys = [
  // row1
  { en: { normal: '`', shifted: '~' }, ru: { normal: 'ё', shifted: 'Ё' }, code: 'Backquote' },
  { en: { normal: '1', shifted: '!' }, ru: { normal: '1', shifted: '!' }, code: 'Digit1' },
  { en: { normal: '2', shifted: '@' }, ru: { normal: '2', shifted: '"' }, code: 'Digit2' },
  { en: { normal: '3', shifted: '#' }, ru: { normal: '3', shifted: '№' }, code: 'Digit3' },
  { en: { normal: '4', shifted: '$' }, ru: { normal: '4', shifted: ';' }, code: 'Digit4' },
  { en: { normal: '5', shifted: '%' }, ru: { normal: '5', shifted: '%' }, code: 'Digit5' },
  { en: { normal: '6', shifted: '^' }, ru: { normal: '6', shifted: ':' }, code: 'Digit6' },
  { en: { normal: '7', shifted: '&' }, ru: { normal: '7', shifted: '?' }, code: 'Digit7' },
  { en: { normal: '8', shifted: '*' }, ru: { normal: '8', shifted: '*' }, code: 'Digit8' },
  { en: { normal: '9', shifted: '(' }, ru: { normal: '9', shifted: '(' }, code: 'Digit9' },
  { en: { normal: '0', shifted: ')' }, ru: { normal: '0', shifted: ')' }, code: 'Digit0' },
  { en: { normal: '-', shifted: '_' }, ru: { normal: '-', shifted: '_' }, code: 'Minus' },
  { en: { normal: '=', shifted: '+' }, ru: { normal: '=', shifted: '+' }, code: 'Equal' },
  {
    en: { normal: 'Backspace', shifted: 'Backspace' },
    ru: { normal: 'Backspace', shifted: 'Backspace' },
    code: 'Backspace',
  },
  // row 2
  { en: { normal: 'Tab', shifted: 'Tab' }, ru: { normal: 'Tab', shifted: 'Tab' }, code: 'Tab' },
  { en: { normal: 'q', shifted: 'Q' }, ru: { normal: 'й', shifted: 'Й' }, code: 'KeyQ' },
  { en: { normal: 'w', shifted: 'W' }, ru: { normal: 'ц', shifted: 'Ц' }, code: 'KeyW' },
  { en: { normal: 'e', shifted: 'E' }, ru: { normal: 'у', shifted: 'У' }, code: 'KeyE' },
  { en: { normal: 'r', shifted: 'R' }, ru: { normal: 'к', shifted: 'К' }, code: 'KeyR' },
  { en: { normal: 't', shifted: 'T' }, ru: { normal: 'е', shifted: 'Е' }, code: 'KeyT' },
  { en: { normal: 'y', shifted: 'Y' }, ru: { normal: 'н', shifted: 'Н' }, code: 'KeyY' },
  { en: { normal: 'u', shifted: 'U' }, ru: { normal: 'г', shifted: 'Г' }, code: 'KeyU' },
  { en: { normal: 'i', shifted: 'I' }, ru: { normal: 'ш', shifted: 'Ш' }, code: 'KeyI' },
  { en: { normal: 'o', shifted: 'O' }, ru: { normal: 'щ', shifted: 'Щ' }, code: 'KeyO' },
  { en: { normal: 'p', shifted: 'P' }, ru: { normal: 'з', shifted: 'З' }, code: 'KeyP' },
  { en: { normal: '[', shifted: '{' }, ru: { normal: 'х', shifted: 'Х' }, code: 'BracketLeft' },
  { en: { normal: ']', shifted: '}' }, ru: { normal: 'ъ', shifted: 'Ъ' }, code: 'BracketRight' },
  { en: { normal: '\\', shifted: '|' }, ru: { normal: '\\', shifted: '/' }, code: 'Backslash' },
  { en: { normal: 'del', shifted: 'del' }, ru: { normal: 'del', shifted: 'del' }, code: 'Delete' },

  // row 3
  {
    en: { normal: 'CapsLock', shifted: 'CapsLock' },
    ru: { normal: 'CapsLock', shifted: 'CapsLock' },
    code: 'CapsLock',
  },
  { en: { normal: 'a', shifted: 'A' }, ru: { normal: 'ф', shifted: 'Ф' }, code: 'KeyA' },
  { en: { normal: 's', shifted: 'S' }, ru: { normal: 'ы', shifted: 'Ы' }, code: 'KeyS' },
  { en: { normal: 'd', shifted: 'D' }, ru: { normal: 'в', shifted: 'В' }, code: 'KeyD' },
  { en: { normal: 'f', shifted: 'F' }, ru: { normal: 'а', shifted: 'А' }, code: 'KeyF' },
  { en: { normal: 'g', shifted: 'G' }, ru: { normal: 'п', shifted: 'П' }, code: 'KeyG' },
  { en: { normal: 'h', shifted: 'H' }, ru: { normal: 'р', shifted: 'Р' }, code: 'KeyH' },
  { en: { normal: 'j', shifted: 'j' }, ru: { normal: 'о', shifted: 'О' }, code: 'KeyJ' },
  { en: { normal: 'k', shifted: 'K' }, ru: { normal: 'л', shifted: 'Л' }, code: 'KeyK' },
  { en: { normal: 'l', shifted: 'L' }, ru: { normal: 'д', shifted: 'Д' }, code: 'KeyL' },
  { en: { normal: ';', shifted: ':' }, ru: { normal: 'ж', shifted: 'Ж' }, code: 'Semicolon' },
  { en: { normal: "'", shifted: '"' }, ru: { normal: 'э', shifted: 'Э' }, code: 'Quote' },
  {
    en: { normal: 'Enter', shifted: 'Enter' },
    ru: { normal: 'Enter', shifted: 'Enter' },
    code: 'Enter',
  },

  // row 4
  {
    en: { normal: 'Shift Left', shifted: 'Shift Left' },
    ru: { normal: 'Shift Left', shifted: 'Shift Left' },
    code: 'ShiftLeft',
  },
  { en: { normal: 'z', shifted: 'Z' }, ru: { normal: 'я', shifted: 'Я' }, code: 'KeyZ' },
  { en: { normal: 'x', shifted: 'X' }, ru: { normal: 'ч', shifted: 'Ч' }, code: 'KeyX' },
  { en: { normal: 'c', shifted: 'C' }, ru: { normal: 'с', shifted: 'С' }, code: 'KeyC' },
  { en: { normal: 'v', shifted: 'V' }, ru: { normal: 'м', shifted: 'М' }, code: 'KeyV' },
  { en: { normal: 'b', shifted: 'B' }, ru: { normal: 'и', shifted: 'И' }, code: 'KeyB' },
  { en: { normal: 'n', shifted: 'N' }, ru: { normal: 'т', shifted: 'Т' }, code: 'KeyN' },
  { en: { normal: 'm', shifted: 'M' }, ru: { normal: 'ь', shifted: 'Ь' }, code: 'KeyM' },
  { en: { normal: ',', shifted: '<' }, ru: { normal: 'б', shifted: 'Б' }, code: 'Comma' },
  { en: { normal: '.', shifted: '>' }, ru: { normal: 'ю', shifted: 'Ю' }, code: 'Period' },
  { en: { normal: '/', shifted: '?' }, ru: { normal: '.', shifted: ',' }, code: 'Slash' },
  { en: { normal: '↑', shifted: '↑' }, ru: { normal: '↑', shifted: '↑' }, code: 'ArrowUp' },
  {
    en: { normal: 'Shift Right', shifted: 'Shift Right' },
    ru: { normal: 'Shift Right', shifted: 'Shift Right' },
    code: 'ShiftRight',
  },
  {
    en: { normal: 'Ctrl', shifted: 'Ctrl' },
    ru: { normal: 'Ctrl', shifted: 'Ctrl' },
    code: 'ControlLeft',
  },
  {
    en: { normal: 'Win', shifted: 'Win' },
    ru: { normal: 'Win', shifted: 'Win' },
    code: 'MetaLeft',
  },
  { en: { normal: 'Alt', shifted: 'Alt' }, ru: { normal: 'Alt', shifted: 'Alt' }, code: 'AltLeft' },
  {
    en: { normal: 'Spacebar', shifted: 'Spacebar' },
    ru: { normal: 'Spacebar', shifted: 'Spacebar' },
    code: 'Space',
  },
  {
    en: { normal: 'Alt', shifted: 'Alt' },
    ru: { normal: 'Alt', shifted: 'Alt' },
    code: 'AltRight',
  },
  { en: { normal: '←', shifted: '←' }, ru: { normal: '←', shifted: '←' }, code: 'ArrowLeft' },
  { en: { normal: '↓', shifted: '↓' }, ru: { normal: '↓', shifted: '↓' }, code: 'ArrowDown' },
  { en: { normal: '→', shifted: '→' }, ru: { normal: '→', shifted: '→' }, code: 'ArrowRight' },
  {
    en: { normal: 'Ctrl', shifted: 'Ctrl' },
    ru: { normal: 'Ctrl', shifted: 'Ctrl' },
    code: 'ControlRight',
  },
];

export default keys;
